# Generated by Django 3.1.6 on 2021-02-09 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('api_backend', '0002_auto_20210209_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authtoken.token'),
        ),
    ]
