# Generated by Django 3.1.6 on 2021-02-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_backend', '0004_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Balance',
            new_name='balance',
        ),
    ]
